import { environment } from 'src/environments/environment';

export const apiConstants = {
	login: environment.origin + 'user/login',
	registration: environment.origin + 'user/register',
	isEmailUnique: environment.origin + 'user/isEmailUnique',
	fastPosting: environment.origin + 'job/createjob',
	getProfile: environment.origin + 'user/profile',
	updateProfile: environment.origin + 'user/update',
	deleteDocument: environment.origin + 'user/document/delete',
	profileDetalis: environment.origin + 'user/get',
	userDetails: environment.origin + 'user/getUserdetails',
	home: environment.origin + 'home',
	saveAboutMe: environment.origin + 'user/aboutme/save',
	getAboutMe: environment.origin + 'user/aboutme/get',
	jobPosting: environment.origin + 'job/postjob',
	getTimeSheet: environment.origin + 'user/timesheet/get',
	storeTimeSheet: environment.origin + 'user/timesheet/store',
	transaction: environment.origin + 'booking/store',
	reservation: environment.origin + 'booking/message/store',
	review: environment.origin + 'user/review/store',
	userSubscribe: environment.origin + 'subscribe',
	getTimeSheetByUserId: environment.origin + 'user/timesheet/getbyid',
	storeUserHireDay: environment.origin + 'storeUserHireDay',
	contactus: environment.origin + 'contactus',
	stripePayment: environment.origin + 'stripePayment',
	userlist: environment.origin + 'chat/getusers',
	getMessageListByUserId: environment.origin + 'chat/getuserchat',
	homeSearchFilter: environment.origin + 'home/search',
	homeRangeFilter: environment.origin + 'home/filter',
	getReview: environment.origin + 'user/review/get',
	tokenVerify: environment.origin + 'token-verify',
	getTimeSheetHour: environment.origin + 'user/timesheet/custom',
	forgotpassword: environment.origin + 'user/forgotpassword',
	resetpassword: environment.origin + 'user/resetpassword',
	blog: environment.origin + 'blog',
	getUserAllDetails: environment.origin + 'user/useralldetails',
	checkUserJobPost: environment.origin + 'user/checkuserjobpost',
	storeMessageByJobId:environment.origin + 'user/storemessagebyjobid',
	getUserDetailsByJobId:environment.origin + "user/getuserdetailsbyjobid",
	getBlogById:environment.origin + "getblogbyid",
	getAllBlog:environment.origin + "getallblog",
	addUserChat:environment.origin + "adduserchat",
	getJobDetailsById:environment.origin + "getjobdetailsbyid",
	socialLogin:environment.origin + "user/sociallogin",
	sendMessagePostJobUser:environment.origin + "user/sendmessagepostjobuser",
	getAllLocation:environment.origin + "getAllLocation",
	getTimeSheetByStartDate:environment.origin + "user/timesheet/startdate",
	getUserTimesheet:environment.origin + "user/timesheet",
	sendUserNotificationForJob:environment.origin + "sendusernotificationforjob",
	addCustomTime:environment.origin + "addcustomtime",
	userChatStatus:environment.origin + "userchatstatus",
	opayPayment: environment.origin + 'opayPayment',
	changePaymentStatus: environment.origin + 'changePaymentStatus',
	getjobreviewbyid: environment.origin + 'getjobreviewbyid',
	countmessage: environment.origin + 'countmessage',
};
